// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotCommand_message.proto

#ifndef PROTOBUF_RobotCommand_5fmessage_2eproto__INCLUDED
#define PROTOBUF_RobotCommand_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "position_message.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RobotCommand_5fmessage_2eproto();
void protobuf_AssignDesc_RobotCommand_5fmessage_2eproto();
void protobuf_ShutdownFile_RobotCommand_5fmessage_2eproto();

class RobotCommand_message;

// ===================================================================

class RobotCommand_message : public ::google::protobuf::Message {
 public:
  RobotCommand_message();
  virtual ~RobotCommand_message();

  RobotCommand_message(const RobotCommand_message& from);

  inline RobotCommand_message& operator=(const RobotCommand_message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotCommand_message& default_instance();

  void Swap(RobotCommand_message* other);

  // implements Message ----------------------------------------------

  RobotCommand_message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RobotCommand_message& from);
  void MergeFrom(const RobotCommand_message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .position_message fin_pos = 1;
  inline bool has_fin_pos() const;
  inline void clear_fin_pos();
  static const int kFinPosFieldNumber = 1;
  inline const ::position_message& fin_pos() const;
  inline ::position_message* mutable_fin_pos();
  inline ::position_message* release_fin_pos();
  inline void set_allocated_fin_pos(::position_message* fin_pos);

  // required .position_message fin_vel = 2;
  inline bool has_fin_vel() const;
  inline void clear_fin_vel();
  static const int kFinVelFieldNumber = 2;
  inline const ::position_message& fin_vel() const;
  inline ::position_message* mutable_fin_vel();
  inline ::position_message* release_fin_vel();
  inline void set_allocated_fin_vel(::position_message* fin_vel);

  // required float maxSpeed = 3;
  inline bool has_maxspeed() const;
  inline void clear_maxspeed();
  static const int kMaxSpeedFieldNumber = 3;
  inline float maxspeed() const;
  inline void set_maxspeed(float value);

  // required float kickspeedx = 4;
  inline bool has_kickspeedx() const;
  inline void clear_kickspeedx();
  static const int kKickspeedxFieldNumber = 4;
  inline float kickspeedx() const;
  inline void set_kickspeedx(float value);

  // required float kickspeedz = 5;
  inline bool has_kickspeedz() const;
  inline void clear_kickspeedz();
  static const int kKickspeedzFieldNumber = 5;
  inline float kickspeedz() const;
  inline void set_kickspeedz(float value);

  // required bool useNav = 6;
  inline bool has_usenav() const;
  inline void clear_usenav();
  static const int kUseNavFieldNumber = 6;
  inline bool usenav() const;
  inline void set_usenav(bool value);

  // required bool isBallObs = 7;
  inline bool has_isballobs() const;
  inline void clear_isballobs();
  static const int kIsBallObsFieldNumber = 7;
  inline bool isballobs() const;
  inline void set_isballobs(bool value);

  // required bool isKickObs = 8;
  inline bool has_iskickobs() const;
  inline void clear_iskickobs();
  static const int kIsKickObsFieldNumber = 8;
  inline bool iskickobs() const;
  inline void set_iskickobs(bool value);

  // @@protoc_insertion_point(class_scope:RobotCommand_message)
 private:
  inline void set_has_fin_pos();
  inline void clear_has_fin_pos();
  inline void set_has_fin_vel();
  inline void clear_has_fin_vel();
  inline void set_has_maxspeed();
  inline void clear_has_maxspeed();
  inline void set_has_kickspeedx();
  inline void clear_has_kickspeedx();
  inline void set_has_kickspeedz();
  inline void clear_has_kickspeedz();
  inline void set_has_usenav();
  inline void clear_has_usenav();
  inline void set_has_isballobs();
  inline void clear_has_isballobs();
  inline void set_has_iskickobs();
  inline void clear_has_iskickobs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::position_message* fin_pos_;
  ::position_message* fin_vel_;
  float maxspeed_;
  float kickspeedx_;
  float kickspeedz_;
  bool usenav_;
  bool isballobs_;
  bool iskickobs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_RobotCommand_5fmessage_2eproto();
  friend void protobuf_AssignDesc_RobotCommand_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_RobotCommand_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static RobotCommand_message* default_instance_;
};
// ===================================================================


// ===================================================================

// RobotCommand_message

// required .position_message fin_pos = 1;
inline bool RobotCommand_message::has_fin_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RobotCommand_message::set_has_fin_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RobotCommand_message::clear_has_fin_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RobotCommand_message::clear_fin_pos() {
  if (fin_pos_ != NULL) fin_pos_->::position_message::Clear();
  clear_has_fin_pos();
}
inline const ::position_message& RobotCommand_message::fin_pos() const {
  return fin_pos_ != NULL ? *fin_pos_ : *default_instance_->fin_pos_;
}
inline ::position_message* RobotCommand_message::mutable_fin_pos() {
  set_has_fin_pos();
  if (fin_pos_ == NULL) fin_pos_ = new ::position_message;
  return fin_pos_;
}
inline ::position_message* RobotCommand_message::release_fin_pos() {
  clear_has_fin_pos();
  ::position_message* temp = fin_pos_;
  fin_pos_ = NULL;
  return temp;
}
inline void RobotCommand_message::set_allocated_fin_pos(::position_message* fin_pos) {
  delete fin_pos_;
  fin_pos_ = fin_pos;
  if (fin_pos) {
    set_has_fin_pos();
  } else {
    clear_has_fin_pos();
  }
}

// required .position_message fin_vel = 2;
inline bool RobotCommand_message::has_fin_vel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RobotCommand_message::set_has_fin_vel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RobotCommand_message::clear_has_fin_vel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RobotCommand_message::clear_fin_vel() {
  if (fin_vel_ != NULL) fin_vel_->::position_message::Clear();
  clear_has_fin_vel();
}
inline const ::position_message& RobotCommand_message::fin_vel() const {
  return fin_vel_ != NULL ? *fin_vel_ : *default_instance_->fin_vel_;
}
inline ::position_message* RobotCommand_message::mutable_fin_vel() {
  set_has_fin_vel();
  if (fin_vel_ == NULL) fin_vel_ = new ::position_message;
  return fin_vel_;
}
inline ::position_message* RobotCommand_message::release_fin_vel() {
  clear_has_fin_vel();
  ::position_message* temp = fin_vel_;
  fin_vel_ = NULL;
  return temp;
}
inline void RobotCommand_message::set_allocated_fin_vel(::position_message* fin_vel) {
  delete fin_vel_;
  fin_vel_ = fin_vel;
  if (fin_vel) {
    set_has_fin_vel();
  } else {
    clear_has_fin_vel();
  }
}

// required float maxSpeed = 3;
inline bool RobotCommand_message::has_maxspeed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RobotCommand_message::set_has_maxspeed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RobotCommand_message::clear_has_maxspeed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RobotCommand_message::clear_maxspeed() {
  maxspeed_ = 0;
  clear_has_maxspeed();
}
inline float RobotCommand_message::maxspeed() const {
  return maxspeed_;
}
inline void RobotCommand_message::set_maxspeed(float value) {
  set_has_maxspeed();
  maxspeed_ = value;
}

// required float kickspeedx = 4;
inline bool RobotCommand_message::has_kickspeedx() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RobotCommand_message::set_has_kickspeedx() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RobotCommand_message::clear_has_kickspeedx() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RobotCommand_message::clear_kickspeedx() {
  kickspeedx_ = 0;
  clear_has_kickspeedx();
}
inline float RobotCommand_message::kickspeedx() const {
  return kickspeedx_;
}
inline void RobotCommand_message::set_kickspeedx(float value) {
  set_has_kickspeedx();
  kickspeedx_ = value;
}

// required float kickspeedz = 5;
inline bool RobotCommand_message::has_kickspeedz() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RobotCommand_message::set_has_kickspeedz() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RobotCommand_message::clear_has_kickspeedz() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RobotCommand_message::clear_kickspeedz() {
  kickspeedz_ = 0;
  clear_has_kickspeedz();
}
inline float RobotCommand_message::kickspeedz() const {
  return kickspeedz_;
}
inline void RobotCommand_message::set_kickspeedz(float value) {
  set_has_kickspeedz();
  kickspeedz_ = value;
}

// required bool useNav = 6;
inline bool RobotCommand_message::has_usenav() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RobotCommand_message::set_has_usenav() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RobotCommand_message::clear_has_usenav() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RobotCommand_message::clear_usenav() {
  usenav_ = false;
  clear_has_usenav();
}
inline bool RobotCommand_message::usenav() const {
  return usenav_;
}
inline void RobotCommand_message::set_usenav(bool value) {
  set_has_usenav();
  usenav_ = value;
}

// required bool isBallObs = 7;
inline bool RobotCommand_message::has_isballobs() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RobotCommand_message::set_has_isballobs() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RobotCommand_message::clear_has_isballobs() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RobotCommand_message::clear_isballobs() {
  isballobs_ = false;
  clear_has_isballobs();
}
inline bool RobotCommand_message::isballobs() const {
  return isballobs_;
}
inline void RobotCommand_message::set_isballobs(bool value) {
  set_has_isballobs();
  isballobs_ = value;
}

// required bool isKickObs = 8;
inline bool RobotCommand_message::has_iskickobs() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RobotCommand_message::set_has_iskickobs() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RobotCommand_message::clear_has_iskickobs() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RobotCommand_message::clear_iskickobs() {
  iskickobs_ = false;
  clear_has_iskickobs();
}
inline bool RobotCommand_message::iskickobs() const {
  return iskickobs_;
}
inline void RobotCommand_message::set_iskickobs(bool value) {
  set_has_iskickobs();
  iskickobs_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RobotCommand_5fmessage_2eproto__INCLUDED
